#include "unity/fixture/unity_fixture.h"

TEST_GROUP_RUNNER(menu_lib_init)
{
    /* Test cases to run */
    RUN_TEST_CASE(menu_lib_init, WhenMenuInitThenReturnOk);

    RUN_TEST_CASE(menu_lib_init, WhenMenuInitThenMenuScreenSizeEqualToPassedConfigDataColumnCountAndRowCount);
    RUN_TEST_CASE(menu_lib_init, WhenMenuInitThenMenuScreenDriverInterfaceisEqualToMockMenuScreenDriverInterface);

    RUN_TEST_CASE(menu_lib_init, WhenMenuViewInitWithoutInitThenReturnNotInitialized);
    RUN_TEST_CASE(menu_lib_init, WhenMenuViewInitWithNullRootMenuThenReturnNoMenu);
    RUN_TEST_CASE(menu_lib_init, WhenMenuViewInitWithTooDeepMenuThenReturnMenuDepthTooShallow);
    RUN_TEST_CASE(menu_lib_init, WhenMenuViewInitWithValidMenuThenReturnOk);

    RUN_TEST_CASE(menu_lib_init, WhenInitWithValidDisplayThenReturnOk);
    RUN_TEST_CASE(menu_lib_init, GivenMockMenuScreenInitStatusEqualMenuScreenInitUnknownWhenInitWithValidDisplayThenMockScreenInitStatusEqualMenuScreenInitOk); 
    RUN_TEST_CASE(menu_lib_init, WhenInitWithNullDisplayThenReturnNoDisplayInterface);
    RUN_TEST_CASE(menu_lib_init, WhenInitWithIncompleteDisplayThenReturnIncompleteInterface);
}

TEST_GROUP_RUNNER(menu_lib)
{
    /* MENU entry Init View Test cases to run */
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenWhenMenuViewInitForMockMenuCalledThenScreenContentIsEqualToExpected);
    /* MENU ESC on top level Test cases to run */
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndTopLevelEscCbRegisteredWhenMenuEscCalledThenTopLevelEscCbExecuted);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndTopLevelEscCbNotRegisteredWhenMenuEscCalledThenTopLevelEscCbStatusIsEqualToUnknown);
    /* MENU NEXT on top level menu Test cases to run */
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuWhenMenuNextCalledThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuWhenMenuNextCalledTwiceThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuWhenMenuNextCalled3TimesThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuWhenMenuNextCalled4TimesThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuWhenMenuNextCalled5TimesThenScreenContentIsEqualToExpected);

    /* MENU PREV on top level menu Test cases to run */
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled100TimesWhenMenuPrevCalledOnceThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled100TimesWhenMenuPrevCalledTwiceThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled100TimesWhenMenuPrevCalled3TimesThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled100TimesWhenMenuPrevCalled4TimesThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled100TimesWhenMenuPrevCalled5TimesThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled100TimesWhenMenuPrevCalled100TimesThenScreenContentIsEqualToExpected);
    /* MENU NEXT & PREV combination on top level menu Test cases to run */
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledOnceWhenMenuPrevCalledOnceThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledTwiceWhenMenuPrevCalledTwiceThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled3TimesWhenMenuPrevCalled3TimesThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledTwiceWhenMenuPrevCalledOnceThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled3TimesWhenMenuPrevCalledOnceThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled3TimesWhenMenuPrevCalledTwiceThenScreenContentIsEqualToExpected);

    /* MENU ENTER on top level Test cases to run */
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuWhenMenuEnterCalledThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockAndMenuNextCalledMenuWhenMenuEnterCalledThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockAndMenuNext50TimesCalledMenuWhenMenuEnterCalledThenScreenContentIsEqualToExpected);

    /* MENU ENTER & NEXT & PREV to 1'st level menu Test cases to run */
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledAndMenuEnterCalledWhenMenuNextCalledOnceThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledAndMenuEnterCalledWhenMenuNextCalled50TimesThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledAndMenuEnterCalledAndMenuNextCalled50TimesWhenMenuPrevCalled2TimesThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledAndMenuEnterCalledAndMenuNextCalled50TimesWhenMenuPrevCalled10TimesThenScreenContentIsEqualToExpected);

    /* MENU ENTER & NEXT & PREV on 2'st level menu Test cases to run */
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledAndMenuEnterCalledTwiceWhenMenuNextCalledOnceThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledAndMenuEnterCalledTwiceWhenMenuNextCalled50TimesThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledAndMenuEnterCalledTwiceAndMenuNextCalled50TimesWhenMenuPrevCalled2TimesThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledAndMenuEnterCalledTwiceAndMenuNextCalled50TimesWhenMenuPrevCalled10TimesThenScreenContentIsEqualToExpected);

    /* MENU ENTER & NEXT & PREV to 3'rd level menu Test cases to run */
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledAndMenuEnterCalled3TimesWhenMenuNextCalledOnceThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledAndMenuEnterCalled3TimesWhenMenuNextCalled50TimesThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledAndMenuEnterCalled3TimesAndMenuNextCalled50TimesWhenMenuPrevCalled2TimesThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledAndMenuEnterCalled3TimesAndMenuNextCalled50TimesWhenMenuPrevCalled10TimesThenScreenContentIsEqualToExpected);

    /* MENU ENTER & NEXT & PREV & ESC different Test cases to run */
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledAndMenuEnterCalledAndMenuNextCalleWhenMenuEscCalleddOnceThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalledAndMenuEnterCalledAndMenuNextCalleWhenMenuEscCalledd10TimesThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled5TimesAndMenuPrevCalled3TimesAndMenuEnterCalledTwiceAndMenuNextCalled3TimesAndMenuPrevCalledOnceAndMenuEntrCalledOnceWhenMenuNextCalledOnceThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled5TimesAndMenuPrevCalled3TimesAndMenuEnterCalledTwiceAndMenuNextCalled3TimesAndMenuPrevCalledOnceAndMenuEntrCalledOnceAndMenuNextCalledOnceWhenMenuEscCalledOnceThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled5TimesAndMenuPrevCalled3TimesAndMenuEnterCalledTwiceAndMenuNextCalled3TimesAndMenuPrevCalledOnceAndMenuEntrCalledOnceAndMenuNextCalledOnceWhenMenuEscCalledTwiceThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled5TimesAndMenuPrevCalled3TimesAndMenuEnterCalledTwiceAndMenuNextCalled3TimesAndMenuPrevCalledOnceAndMenuEntrCalledOnceAndMenuNextCalledOnceWhenMenuEscCalled3TimesThenScreenContentIsEqualToExpected);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled5TimesAndMenuPrevCalled3TimesAndMenuEnterCalledTwiceAndMenuNextCalled3TimesAndMenuPrevCalledOnceAndMenuEntrCalledOnceAndMenuNextCalledOnceWhenMenuEscCalled10TimesThenScreenContentIsEqualToExpected);

    /* MENU callback execution Test cases to run */
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled5TimesAndMenuPrevCalled3TimesAndMenuEnterCalledTwiceAndMenuNextCalled3TimesAndMenuPrevCalledOnceAndMockMenuCalblackStatusSetToUnknownWhenMenuEnterCalleddTwiceThenMockMenuCalblackStatusIsEqualToCbExecuted);
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled5TimesAndMockMenuCalblackStatusSetToUnknownWhenMenuEnterCalleddOnceThenMockMenuCalblackStatusIsEqualToUnknown);

    /* MENU get current posisiotn test cases to run */
    RUN_TEST_CASE(menu_lib, GivenMenuInitWith2004ScreenAndMenuViewInitForMockMenuAndMenuNextCalled2TimesWhenGetCurrentMenuPositionCalledThenReturnetValueIsEqualToMockMenu3);
    // important to check if enter scrren are same as exit screen (menu view and cursor position)
}
